# Generated by Django 4.1 on 2022-09-21 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywatchlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistabdi',
            name='release_date',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='wishlistabdi',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
