# Generated by Django 4.1 on 2022-09-21 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywatchlist', '0002_alter_wishlistabdi_release_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistabdi',
            name='release_date',
            field=models.CharField(max_length=11),
        ),
    ]
