# Generated by Django 4.1 on 2022-09-21 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mywatchlist', '0003_alter_wishlistabdi_release_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WishlistAbdi',
            new_name='WatchlistAbdi',
        ),
    ]
